username = input("Please, enter your username: ")
print(f"Hi, {username}! Welcome!")
print("We are learning Git!")
print("Another line!")
print("Now, we learning GitHub!")
print("Our project: Laptop_config")